import { MapPin, Zap, Leaf, BarChart3, Phone, Mail, Fish, Shield, Megaphone, Users, Activity } from 'lucide-react'

export const siteConfig = {
  name: 'Delta Systematics',
  description: 'Environmental Consulting & GIS Solutions',
  contact: {
    phones: ['+234 803 338 6435', '+234 803 308 8811'],
    email: 'info@deltasystematics.com',
  },
}

export const navLinks = [
  { label: 'Home', href: '/' },
  { label: 'Services', href: '/services' },
  { label: 'Projects', href: '/projects' },
  { label: 'About', href: '/about' },
]

export const services = [
  {
    id: 'gis-solutions',
    icon: MapPin,
    title: 'Geographic Information Systems',
    description: 'Advanced GIS solutions for spatial analysis, mapping, and data visualization.',
    color: 'from-blue-600 to-cyan-500',
  },
  {
    id: 'remote-sensing',
    icon: Zap,
    title: 'Remote Sensing Services',
    description: 'Cutting-edge remote sensing and image processing for environmental monitoring.',
    color: 'from-amber-500 to-orange-600',
  },
  {
    id: 'environmental-consulting',
    icon: Leaf,
    title: 'Environmental Consulting',
    description: 'Comprehensive environmental impact assessments and sustainable solutions.',
    color: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'geospatial-analytics',
    icon: BarChart3,
    title: 'Geospatial Analytics',
    description: 'Data-driven insights for informed decision-making and strategic planning.',
    color: 'from-indigo-600 to-purple-600',
  },
  {
    id: 'fisheries-food-security',
    icon: Fish,
    title: 'Fisheries & Food Security',
    description: 'Innovative solutions for sustainable fisheries management and food security enhancement.',
    color: 'from-blue-400 to-blue-600',
  },
  {
    id: 'geofencing-geoframing',
    icon: Shield,
    title: 'Geofencing & Geoframing',
    description: 'Advanced security and location-based intelligence through precise geospatial technology.',
    color: 'from-slate-600 to-slate-800',
  },
  {
    id: 'advertisement-marketing',
    icon: Megaphone,
    title: 'Advertisement & Marketing',
    description: 'Targeted marketing strategies powered by geospatial data and behavior analysis.',
    color: 'from-pink-500 to-rose-600',
  },
  {
    id: 'social-engineering',
    icon: Users,
    title: 'Social Engineering',
    description: 'Understanding social dynamics for sustainable community development and insights.',
    color: 'from-orange-400 to-amber-600',
  },
  {
    id: 'sustainable-health-systems',
    icon: Activity,
    title: 'Sustainable Health Systems',
    description: 'Resilient health systems through data-driven planning and spatial health analytics.',
    color: 'from-emerald-400 to-green-600',
  },
]

export const projects = [
  {
    id: '1',
    title: 'Environmental Sensitivity Index (ESI) Mapping',
    location: 'Alakiri Area',
    category: 'Mapping & Analysis',
    description:
      'ESI mapping to determine the vulnerability of nearby environment to existing oil facilities in the Alakiri area.',
    details:
      'Advanced GIS mapping used to assess environmental sensitivity and establish baseline environmental conditions for infrastructure development.',
    fullDescription: 'This comprehensive Environmental Sensitivity Index (ESI) mapping project was designed to assess the vulnerability of the Alakiri area\'s environment to potential impacts from existing and proposed oil extraction facilities. Using advanced GIS technology and satellite imagery analysis, we developed a detailed environmental sensitivity framework that identifies critical ecological zones and vulnerable habitats.',
    objectives: [
      'Create detailed environmental sensitivity maps for the Alakiri region',
      'Identify critical ecological zones and vulnerable habitats',
      'Establish baseline environmental conditions for future monitoring',
      'Support environmental impact assessment and planning decisions',
      'Develop recommendations for sustainable facility management',
    ],
    methodology: [
      'Satellite imagery acquisition and processing from multiple time periods',
      'Field surveys to validate remote sensing data',
      'GIS spatial analysis and multi-criteria overlay analysis',
      'Integration of environmental, ecological, and infrastructure data',
      'Stakeholder consultation and validation workshops',
    ],
    outcomes: [
      'Comprehensive ESI maps covering the entire Alakiri area',
      'Identified 5 high-sensitivity zones requiring special protection',
      'Established baseline environmental data for future monitoring',
      'Provided recommendations for facility operations and environmental management',
      'Enhanced stakeholder understanding of environmental vulnerabilities',
    ],
    client: 'Oil & Gas Operator',
    year: '2015',
    team: '8 specialists',
    color: 'primary',
    image: '/projects/esi_mapping_project.png',
  },
  {
    id: '2',
    title: 'Land Use Mapping and Resource Assessments',
    location: 'Niger Delta Survey',
    category: 'Remote Sensing',
    description:
      'Satellite imagery analysis to measure the quantity and quality of habitats in a regional survey of the Niger Delta.',
    details:
      'Comprehensive landuse mapping using satellite imagery to evaluate habitat quality and environmental resource distribution across the Niger Delta region.',
    fullDescription: 'A large-scale regional survey utilizing advanced satellite remote sensing technology to map land use patterns and assess environmental resources across the Niger Delta. This project involved multi-temporal analysis of satellite imagery to track changes in habitat quality and resource distribution, providing critical data for regional environmental planning.',
    objectives: [
      'Map current land use patterns across the Niger Delta',
      'Assess habitat quality and biodiversity distribution',
      'Evaluate environmental resource availability',
      'Monitor changes in land use over time',
      'Support regional environmental planning initiatives',
    ],
    methodology: [
      'Multi-spectral satellite imagery classification',
      'Field validation surveys across representative areas',
      'Temporal analysis of land use changes',
      'Habitat quality assessment using ecological indicators',
      'Resource inventory and mapping',
    ],
    outcomes: [
      'Detailed land use classification map covering Niger Delta region',
      'Identification of 12 major habitat types',
      'Quantified resource distribution and availability',
      'Documented land use changes over 10-year period',
      'Generated insights for sustainable resource management',
    ],
    client: 'NDDC/Environmental Ministry',
    year: '2016',
    team: '12 specialists',
    color: 'secondary',
    image: '/projects/land_use_mapping_project.png',
  },
  {
    id: '3',
    title: 'Bathymetric Analysis',
    location: 'Imo River',
    category: 'Geospatial Analysis',
    description:
      'Satellite imagery used to determine the bathymetric profile of the Imo River mouth to support pipeline engineering planning.',
    details:
      'Detailed underwater topography analysis utilizing satellite remote sensing to inform critical infrastructure planning and development.',
    fullDescription: 'A specialized bathymetric analysis project that used advanced satellite remote sensing and hydrographic survey techniques to map the underwater topography of the Imo River mouth. This detailed underwater mapping was essential for engineering design of subsea pipelines and other offshore infrastructure.',
    objectives: [
      'Map underwater topography and bathymetry of Imo River mouth',
      'Identify optimal pipeline routing corridors',
      'Assess seabed stability and sediment characteristics',
      'Support engineering design for subsea infrastructure',
      'Provide navigational safety data',
    ],
    methodology: [
      'Satellite bathymetric data acquisition',
      'Multi-beam sonar surveys',
      'Hydrographic survey data integration',
      'Sediment sampling and analysis',
      '3D bathymetric modeling',
    ],
    outcomes: [
      '3D bathymetric model of Imo River mouth',
      'Identified 3 optimal pipeline routing options',
      'Characterized seabed sediments and stability',
      'Generated navigational and safety recommendations',
      'Supported successful offshore engineering projects',
    ],
    client: 'Oil & Gas Pipeline Operator',
    year: '2014',
    team: '6 specialists',
    color: 'accent',
    image: '/projects/bathymetric_analysis_project.png',
  },
  {
    id: '4',
    title: 'Contingency Plan/Risk Management Operations',
    location: 'SPDC Port Harcourt',
    category: 'Risk Assessment',
    description:
      'GIS-based helicopter response time modeling to predict minimum response time to oil spill incidents.',
    details:
      'Strategic GIS analysis to optimize emergency response planning and establish protocols for rapid environmental incident containment.',
    fullDescription: 'A critical risk management project that developed GIS-based response time modeling to optimize emergency response to potential oil spill incidents in the Port Harcourt operations area. The analysis identified optimal helicopter deployment locations and established response protocols to minimize environmental impact.',
    objectives: [
      'Model helicopter response times to incident locations',
      'Identify optimal emergency response facility locations',
      'Develop rapid response protocols',
      'Assess coverage gaps in emergency infrastructure',
      'Support contingency planning and preparedness',
    ],
    methodology: [
      'GIS network analysis and routing optimization',
      'Helicopter flight time modeling',
      'Incident probability and impact assessment',
      'Multi-criteria analysis for facility location',
      'Scenario planning and simulation',
    ],
    outcomes: [
      'Response time prediction maps for entire operations area',
      'Identified 2 optimal new facility locations',
      'Reduced average response time by 25%',
      'Established rapid response protocols',
      'Enhanced incident preparedness and safety',
    ],
    client: 'Shell Petroleum Development Company',
    year: '2013',
    team: '5 specialists',
    color: 'primary',
    image: '/projects/risk_management_project.png',
  },
  {
    id: '5',
    title: 'AIRTEL Nigeria Network Mapping',
    location: 'South East Zone',
    category: 'Network Infrastructure',
    description:
      'GIS mapping of all ducts and fiber networks in Nigeria, focusing on the South East Zone along the Asaba-Enugu Route.',
    details:
      'Comprehensive GIS inventory and mapping of telecommunications infrastructure including ducts, fiber networks, and system components.',
    fullDescription: 'A large-scale telecommunications infrastructure mapping project for AIRTEL Nigeria, creating a comprehensive GIS-based inventory of all fiber optic cables, ducts, and related infrastructure across the South East Zone, with focus on the critical Asaba-Enugu route.',
    objectives: [
      'Create complete GIS inventory of telecommunications infrastructure',
      'Map fiber optic cable routes and ducts',
      'Document infrastructure specifications and conditions',
      'Support network maintenance and expansion planning',
      'Enable efficient asset management',
    ],
    methodology: [
      'Extensive field surveys of cable routes',
      'GPS positioning of infrastructure elements',
      'Duct and cable condition assessment',
      'Infrastructure attribute database development',
      'Integration with network management systems',
    ],
    outcomes: [
      'Comprehensive telecommunications infrastructure map',
      'Complete asset inventory for 2,500+ km of network',
      'Identified maintenance requirements',
      'Enabled efficient network planning and maintenance',
      'Supported 40% reduction in network downtime',
    ],
    client: 'AIRTEL Nigeria',
    year: '2017',
    team: '15 field specialists',
    color: 'secondary',
    image: '/projects/network_mapping_project.png',
  },
  {
    id: '6',
    title: 'Environmental Sampling and Air/Water Quality Monitoring',
    location: 'OML 58 (Total E&P)',
    category: 'Environmental Monitoring',
    description:
      'Field-based environmental sampling and quality monitoring using specialized equipment for air and water quality assessment.',
    details:
      'Systematic environmental monitoring program including ambient air measurements, headspace sampling, and comprehensive water quality analysis.',
    fullDescription: 'An ongoing environmental monitoring program at the OML 58 facility that combines systematic field sampling with laboratory analysis to track air and water quality in the operational area. The program provides critical baseline data and tracks environmental changes over time.',
    objectives: [
      'Monitor ambient air quality at operational facilities',
      'Assess water quality in surrounding water bodies',
      'Track environmental parameters over time',
      'Identify pollution sources and trends',
      'Support environmental compliance reporting',
    ],
    methodology: [
      'Quarterly ambient air measurements',
      'Water quality sampling and analysis',
      'Headspace gas measurements',
      'Sediment quality assessment',
      'Data management and trend analysis',
    ],
    outcomes: [
      'Established baseline environmental conditions',
      'Monitored 15 environmental parameters over 5 years',
      'Identified and mitigated 3 pollution sources',
      'Supported compliance with environmental regulations',
      'Provided data for environmental reports',
    ],
    client: 'Total Exploration & Production Nigeria',
    year: '2012-2017',
    team: '4 environmental specialists',
    color: 'accent',
    image: '/projects/environmental_monitoring_project.png',
  },
  {
    id: '7',
    title: 'Northern Option Gas Pipeline (NOPL) Air Dispersion Modelling',
    location: 'Total E&P Nigeria Limited',
    category: 'Risk & Environmental',
    description:
      'Quantitative Risk Assessment (QRA) for the 24" natural gas pipeline from Rumuji Node to Imo River intersection.',
    details:
      'Advanced modeling and assessment of potential hazards and risks associated with natural gas pipeline operations and environmental dispersion.',
    fullDescription: 'A comprehensive risk assessment project for a major natural gas pipeline, utilizing advanced air dispersion modeling and quantitative risk analysis to assess potential hazards and environmental impacts of pipeline operations along the 24" NOPL route.',
    objectives: [
      'Conduct quantitative risk assessment of pipeline operations',
      'Model air dispersion from potential gas releases',
      'Identify and assess pipeline hazards',
      'Develop risk mitigation strategies',
      'Support regulatory compliance and approvals',
    ],
    methodology: [
      'Failure mode and effects analysis',
      'Consequence modeling for various release scenarios',
      'Air dispersion modeling with AERMOD',
      'Population vulnerability assessment',
      'Risk ranking and mitigation planning',
    ],
    outcomes: [
      'Completed QRA with 50+ scenarios modeled',
      'Identified 8 major risk factors',
      'Developed mitigation strategies reducing risk by 60%',
      'Obtained regulatory approvals',
      'Established ongoing monitoring protocol',
    ],
    client: 'Total E&P Nigeria Limited',
    year: '2016',
    team: '10 specialists',
    color: 'primary',
    image: '/projects/air_dispersion_project.png',
  },
  {
    id: '8',
    title: 'Environmental Evaluation Report (EER) - Enugu Airport',
    location: 'Federal Airport Authority of Nigeria',
    category: 'Environmental Assessment',
    description:
      'Comprehensive environmental evaluation of Akanu Ibiam International Airport operations and adjoining areas.',
    details:
      'Baseline environmental assessment including water, soil, sediment, air quality, and noise monitoring across airport operations and surrounding ecosystems.',
    fullDescription: 'A comprehensive environmental evaluation report for Akanu Ibiam International Airport that assessed current environmental conditions and monitored potential impacts from airport operations on surrounding communities and ecosystems.',
    objectives: [
      'Establish baseline environmental conditions',
      'Monitor airport operational impacts',
      'Assess air and noise quality',
      'Evaluate water and soil quality',
      'Support sustainable airport operations',
    ],
    methodology: [
      'Baseline environmental surveys',
      'Air quality monitoring with fixed stations',
      'Noise level measurements around airport',
      'Water and soil quality sampling',
      'Noise impact modeling',
    ],
    outcomes: [
      'Comprehensive baseline environmental report',
      'Identified noise impact zones',
      'Characterized water and soil quality',
      'Provided mitigation recommendations',
      'Enabled informed airport planning',
    ],
    client: 'Federal Airport Authority of Nigeria',
    year: '2015',
    team: '8 specialists',
    color: 'secondary',
    image: '/projects/environmental_evaluation_project.png',
  },
  {
    id: '9',
    title: 'Environmental Impact Assessment - Evacuation Road',
    location: 'Mfamosing-Odukpani, Cross River State',
    category: 'EIA',
    description:
      'EIA for 25km road construction project addressing physical, chemical, biological, and socio-economic environmental concerns.',
    details:
      'Comprehensive environmental impact assessment covering all aspects of proposed road development including baseline surveys and mitigation strategies.',
    fullDescription: 'A detailed environmental impact assessment for a 25km evacuation road construction project in Cross River State. The assessment evaluated potential environmental, ecological, and socio-economic impacts of the road development and recommended comprehensive mitigation strategies.',
    objectives: [
      'Assess impacts on forest ecosystems and biodiversity',
      'Evaluate water resource impacts',
      'Assess socio-economic effects on communities',
      'Identify sensitive environmental areas',
      'Develop mitigation and management plans',
    ],
    methodology: [
      'Baseline environmental surveys',
      'Flora and fauna biodiversity assessment',
      'Hydrological and water quality studies',
      'Community consultation and social assessment',
      'Impact prediction and evaluation',
    ],
    outcomes: [
      'Comprehensive EIA report',
      'Identified 5 sensitive ecological zones',
      'Developed alternative routing options',
      'Created biodiversity offset program',
      'Supported project environmental approval',
    ],
    client: 'Cross River State Government',
    year: '2014',
    team: '12 specialists',
    color: 'accent',
    image: '/projects/evacuation_road_eia_project.png',
  },
  {
    id: '10',
    title: 'Brass LNG Dredging and Sand Winning EIA',
    location: 'Brass Island',
    category: 'Environmental Impact',
    description:
      'Environmental impact assessment of dredging and disposal operations for the Brass LNG Project across offshore and coastal areas.',
    details:
      'Extensive survey and assessment including sediment quality, water quality, soil, vegetation, fisheries, geomorphology, and environmental sensitivity analysis.',
    fullDescription: 'A comprehensive environmental impact assessment for large-scale dredging and sand winning operations associated with the Brass LNG Project. The assessment included extensive offshore and coastal surveys to evaluate impacts on marine ecosystems, fisheries, and coastal communities.',
    objectives: [
      'Assess impacts of offshore dredging operations',
      'Evaluate effects on marine ecosystems',
      'Assess fisheries impacts and community effects',
      'Analyze coastal geomorphology changes',
      'Develop environmental management plans',
    ],
    methodology: [
      'Offshore marine surveys and sampling',
      'Sediment and water quality analysis',
      'Fisheries impact assessment',
      'Coastal geomorphology studies',
      'Oil spill risk assessment for dredging operations',
    ],
    outcomes: [
      'Extensive baseline environmental data',
      'Comprehensive impact predictions',
      'Developed operational best practices',
      'Created fisheries offset program',
      'Enabled project environmental authorization',
    ],
    client: 'Brass LNG Development Consortium',
    year: '2016',
    team: '18 specialists',
    color: 'primary',
    image: '/projects/brass_lng_project.png',
  },
  {
    id: '11',
    title: 'GIS Project Monitoring and Evaluation',
    location: 'Niger Delta Development Commission',
    category: 'GIS Monitoring',
    description:
      'GIS-based monitoring and evaluation system for development projects across Niger Delta Commission states.',
    details:
      'Integrated GIS platform for comprehensive project tracking, monitoring, and evaluation across multiple development initiatives.',
    fullDescription: 'A sophisticated GIS-based monitoring and evaluation system developed for the Niger Delta Development Commission (NDDC) to track and monitor multiple development projects across all NDDC states. The system provides real-time project status tracking and performance metrics.',
    objectives: [
      'Create integrated project tracking system',
      'Monitor project progress and performance',
      'Enable data visualization and reporting',
      'Support decision-making processes',
      'Improve project accountability and transparency',
    ],
    methodology: [
      'GIS platform development and customization',
      'Spatial database design and implementation',
      'Web-based portal development',
      'Staff training and capacity building',
      'Ongoing system support and updates',
    ],
    outcomes: [
      'Operational GIS monitoring platform',
      'Real-time tracking of 50+ development projects',
      'Enabled 30% improvement in project oversight',
      'Enhanced transparency and accountability',
      'Supported data-driven decision making',
    ],
    client: 'Niger Delta Development Commission',
    year: '2017-2018',
    team: '10 specialists',
    color: 'secondary',
    image: '/projects/gis_monitoring_project.png',
  },
  {
    id: '12',
    title: 'PHCN Electrical Network Inventory',
    location: 'Ibadan/Ilorin',
    category: 'Infrastructure Mapping',
    description:
      'GIS inventory and mapping of electrical utility networks including poles, transformers, and building footprints.',
    details:
      'Detailed GIS-based inventory of electrical infrastructure including low tension poles, high tension poles, transformers, and associated building structures.',
    fullDescription: 'A comprehensive GIS-based inventory and mapping project of the Power Holding Company of Nigeria (PHCN) electrical network infrastructure across Ibadan and Ilorin. The project created a detailed asset inventory enabling efficient network management and maintenance.',
    objectives: [
      'Create complete electrical network inventory',
      'Map all poles, transformers, and equipment',
      'Document infrastructure specifications',
      'Enable efficient asset management',
      'Support maintenance planning and operations',
    ],
    methodology: [
      'Extensive field surveys with GPS positioning',
      'Infrastructure identification and classification',
      'Equipment specification documentation',
      'Database development and integration',
      'Training on GIS system usage',
    ],
    outcomes: [
      'Complete network map covering both cities',
      'Inventory of 10,000+ poles and transformers',
      'Enabled 25% improvement in maintenance efficiency',
      'Reduced network downtime by 15%',
      'Improved asset tracking and management',
    ],
    client: 'Power Holding Company of Nigeria',
    year: '2015',
    team: '14 field specialists',
    color: 'accent',
    image: '/projects/phcn_network_project.png',
  },
]

export const stats = [
  { label: 'Years of Experience', value: '25+' },
  { label: 'Projects Completed', value: '100+' },
  { label: 'Enterprise Clients', value: '50+' },
]

export const detailedServices = [
  {
    id: 'gis-solutions',
    icon: MapPin,
    title: 'Geographic Information Systems (GIS)',
    description: 'Harness the power of spatial data with our comprehensive GIS solutions.',
    features: [
      'Spatial analysis and modeling',
      'Cartographic design and mapping',
      'Database development and management',
      'System integration and customization',
    ],
    color: 'from-blue-600 to-cyan-500',
  },
  {
    id: 'remote-sensing',
    icon: Zap,
    title: 'Remote Sensing & Image Processing',
    description: 'Advanced satellite imagery analysis for environmental monitoring.',
    features: [
      'Satellite imagery acquisition',
      'Image classification and analysis',
      'Change detection monitoring',
      'Real-time environmental assessment',
    ],
    color: 'from-amber-500 to-orange-600',
  },
  {
    id: 'environmental-consulting',
    icon: Leaf,
    title: 'Environmental Consulting',
    description: 'Expert guidance on environmental challenges and sustainable solutions.',
    features: [
      'Environmental Impact Assessments (EIA)',
      'Environmental Management Systems',
      'Compliance auditing',
      'Sustainability planning',
    ],
    color: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'geospatial-analytics',
    icon: BarChart3,
    title: 'Geospatial Analytics',
    description: 'Data-driven insights for strategic decision-making.',
    features: [
      'Spatial statistical analysis',
      'Predictive modeling',
      'Risk assessment and mapping',
      'Visualization and reporting',
    ],
    color: 'from-indigo-600 to-purple-600',
  },
  {
    id: 'acquisition-audits',
    icon: BarChart3,
    title: 'Acquisition Audits',
    description: 'Comprehensive diligence and property assessment for informed acquisitions.',
    features: [
      'Diligence and property Assessment',
      'Baseline Audit',
      'Comprehensive Cost Allocations',
      'Liability Audits',
      'Identification of Risks and Long-term costs',
    ],
    color: 'from-blue-500 to-indigo-500',
  },
  {
    id: 'air-quality-management',
    icon: Zap,
    title: 'Air Quality Management',
    description: 'Expert air monitoring and impact assessments for regulatory compliance.',
    features: [
      'Air permitting and compliance',
      'Air Quality Control Engineering',
      'Meteorological Monitoring',
      'Emissions Measurements',
      'Air Quality Impact Assessments',
    ],
    color: 'from-sky-400 to-blue-600',
  },
  {
    id: 'site-assessments',
    icon: MapPin,
    title: 'Phase I and II Site Assessments',
    description: 'Thorough investigation and monitoring to identify potential environmental liabilities.',
    features: [
      'Identification of Potential Liabilities',
      'Due Diligence investigations',
      'Investigation Design and Implementation',
      'Soil & Groundwater Monitoring',
    ],
    color: 'from-emerald-400 to-teal-600',
  },
  {
    id: 'geotechnical-surveys',
    icon: Zap,
    title: 'Geotechnical & Hydrological Survey',
    description: 'Advanced groundwater modeling and soil resistivity studies.',
    features: [
      'Groundwater Modeling',
      'Development of Remedial Action Plans',
      'Capital and Operating cost Estimates',
      'Design of Remediation Technology',
      'Soil Resistivity Study',
    ],
    color: 'from-amber-400 to-orange-600',
  },
  {
    id: 'environmental-management',
    icon: Leaf,
    title: 'Environmental Management',
    description: 'Long-term environmental planning and waste reduction strategies.',
    features: [
      'Development of EMS',
      'Long-Term Environmental Planning',
      'Industry Stewardship Programs',
      'Waste Audits and Reduction Strategies',
      'Sustainable Waste Management',
    ],
    color: 'from-green-500 to-emerald-700',
  },
  {
    id: 'compliance-audits',
    icon: BarChart3,
    title: 'Compliance Audits',
    description: 'Assessing regulatory compliance and establishing notification frameworks.',
    features: [
      'Assess Regulatory Compliance',
      'Establish Notification Framework',
      'Assess Good-Management-Practices',
      'Evaluate Staff Preparedness',
    ],
    color: 'from-cyan-500 to-blue-700',
  },
  {
    id: 'risk-assessment',
    icon: BarChart3,
    title: 'Risk Assessment',
    description: 'Human and ecological risk assessment using advanced modeling.',
    features: [
      'Human Toxicology Risk Assessment',
      'Ecological Risk Assessment',
      'Contaminant Fate Modeling',
      'Geostatistics and Data Management',
      'Radiological Risk Assessments',
    ],
    color: 'from-rose-500 to-red-700',
  },
  {
    id: 'water-treatment',
    icon: Leaf,
    title: 'Storm and Wastewater Treatment',
    description: 'Design and evaluation of advanced water treatment systems.',
    features: [
      'Bench-Scale Treatability Studies',
      'Design of Treatment Systems',
      'System Startup and Operation Support',
      'Waste Quality Evaluation',
      'Monitoring and Analysis',
    ],
    color: 'from-blue-400 to-cyan-600',
  },
  {
    id: 'storage-tank-management',
    icon: Zap,
    title: 'Storage Tank Management',
    description: 'Comprehensive underground storage tank investigation and remediation.',
    features: [
      'Site Investigation and Monitoring',
      'Remediation Services',
      'Project Management',
      'Regulatory Liaison',
    ],
    color: 'from-slate-500 to-zinc-700',
  },
  {
    id: 'oil-spill-contingency',
    icon: MapPin,
    title: 'Oil Spill Contingency',
    description: 'Rapid response planning and GIS-based contingency simulation.',
    features: [
      'Cleanup and Disposal Coordination',
      'Contingency Plan Review',
      'Geographic Response Plan development',
      'GIS based Contingency Simulation',
      'Oil Spill Preparedness training',
    ],
    color: 'from-orange-500 to-red-600',
  },
  {
    id: 'oil-gas-services',
    icon: Zap,
    title: 'Oil & Gas Industry Services',
    description: 'Facility design and operation support for the energy sector.',
    features: [
      'Facility Design Support',
      'Construction and Development Services',
      'Facility Operation Support',
      'Site Remediation and Reclamation',
      'Flare Pit Closure',
    ],
    color: 'from-yellow-500 to-orange-700',
  },
  {
    id: 'fisheries-food-security',
    icon: Fish,
    title: 'Fisheries & Food Security',
    description: 'Innovative solutions for sustainable fisheries management and food security enhancement through spatial monitoring.',
    features: [
      'Sustainable catch monitoring',
      'Habitat mapping',
      'Resource management',
      'Food security analytics',
    ],
    color: 'from-blue-400 to-blue-600',
  },
  {
    id: 'geofencing-geoframing',
    icon: Shield,
    title: 'Geofencing & Geoframing',
    description: 'Advanced security and location-based intelligence through precise geofencing and geoframing technologies.',
    features: [
      'Border security systems',
      'Asset tracking',
      'Location-based alerts',
      'Security infrastructure',
    ],
    color: 'from-slate-600 to-slate-800',
  },
  {
    id: 'advertisement-marketing',
    icon: Megaphone,
    title: 'Advertisement & Marketing',
    description: 'Targeted marketing and advertisement strategies powered by geospatial data and consumer behavior analysis.',
    features: [
      'Demographic profiling',
      'Location-based marketing',
      'Campaign performance tracking',
      'Strategic ad placement',
    ],
    color: 'from-pink-500 to-rose-600',
  },
  {
    id: 'social-engineering',
    icon: Users,
    title: 'Social Engineering',
    description: 'Understanding human systems and social dynamics for sustainable community development and behavioral insights.',
    features: [
      'Community impact assessment',
      'Behavioral dynamics analysis',
      'Social system modeling',
      'Strategic communication',
    ],
    color: 'from-orange-400 to-amber-600',
  },
  {
    id: 'sustainable-health-systems',
    icon: Activity,
    title: 'Sustainable Health Systems',
    description: 'Developing resilient and sustainable health systems through data-driven planning and spatial health analytics.',
    features: [
      'Health resource mapping',
      'Epidemiological modeling',
      'Sustainable facility planning',
      'Public health analytics',
    ],
    color: 'from-emerald-400 to-green-600',
  },
]

export const coreValues = [
  {
    title: 'Technical Excellence',
    description: 'Commitment to the highest standards of expertise and innovation in all our projects.',
  },
  {
    title: 'Client Partnership',
    description: 'Collaborative approach focused on understanding and solving our clients\' unique challenges.',
  },
  {
    title: 'Environmental Stewardship',
    description: 'Dedication to sustainable practices and protecting our environment for future generations.',
  },
  {
    title: 'Innovation',
    description: 'Continuous adoption of cutting-edge technologies and methodologies to drive results.',
  },
]

export const partners = [
  { name: 'ESRI Technology', logo: '/logos/esri.jpg' },
  { name: 'Nigerian University Consultancy Services', logo: '/logos/unnconsult.png' },
  { name: 'Space Imaging', logo: '/logos/spaceimaging.jpg' },
  { name: 'IDEAL.com', logo: '/logos/ideal.jpg' },
]

export const clients = [
  { name: 'Shell (SPDC)', logo: '/logos/shell.jpg' },
  { name: 'Total E&P', logo: '/logos/total.jpg' },
  { name: 'ExxonMobil', logo: '/logos/exxonmobil.jpg' },
  { name: 'Addax Petroleum', logo: '/logos/addax.jpg' },
  { name: 'Brass LNG', logo: '/logos/brass.jpg' },
  { name: 'NDDC', logo: '/logos/nddc.jpg' },
  { name: 'National Population Commission (NPC)', logo: '/logos/npc.jpg' },
  { name: 'Federal Airport Authority of Nigeria (FAAN)', logo: '/logos/faan.png' },
  { name: 'UNICEM', logo: '/logos/unicem.png' },
  { name: 'PHCN', logo: '/logos/phcn.png' },
]

export const team = [
  { name: 'Kingsley Achinivu', role: 'CEO' },
  { name: 'John Onwuteaka Ph.D.', role: 'Director Consultancy/QA/QC' },
  { name: 'Alozie Echeonwu (ESQ)', role: 'Legal' },
  { name: 'Sylvester O. Ogbenna', role: 'Accounts/Audit' },
  { name: 'Richard Nwaiwu', role: 'Finance' },
  { name: 'Eyo Mbukpa', role: 'Logistics/Procurement' },
  { name: 'Nnaemeka Okeke', role: 'Business Development/Geomatics' },
  { name: 'Nicholas Onyeka Uyanna', role: 'Admin Officer' },
  { name: 'Denning Nwobosi', role: 'HSE/Operations Manager' },
  { name: 'Choko Prince', role: 'Environmental Officer' },
]

export const disciplines = [
  'Air Quality Engineers',
  'Air Quality Scientists',
  'Auditors',
  'Biologists',
  'Chemists',
  'Environmental Assessors',
  'Geotechnical Engineers',
  'Hydrogeologists',
  'Regulatory Specialists',
  'Risk Analysts',
  'Soil Scientists',
  'Toxicologists',
]
